### PR TITLE
feat(src/plugin): Created plugin that registers module and attaches a…

### PR DESCRIPTION
**Pull request by glemmaPaul**
… property for easy methods

feat(src/module): Added clear action and mutation

feat(src/index): Added plugin as default property

feat(basic/App): Updated example with information about the project

### CODE REVIEW

**Comment by glemmaPaul** [comment]
@ktsn Hi, nice to e-meet you.

First of all I want to thank you for the amazing vuex project you made here, I think it's a well done implementation of abstraction. I wanted to contribute in a way that helps get this project hopefully more used by the vuex community. That's why I wanted to add more clarity to the project with more examples and create an easy way of installing the module.

In this PR there is a new plugin that can be attached to Vue. This on itself adds a `$modal` property to the components that has these helper functions to use. The other work is done in the documentation and examples, they are now more descriptive to usage and examples. I will add github pages deploy command later so it can be shown as example more easily.

Let me know what you think and if you have any advice to go further, thanks :) !

**Comment by glemmaPaul** [comment]
@ktsn ping! I’m curious to know if I can help you further

**Comment by ktsn** [comment]
Thank you for the contribution. However, I'm not a fan of adding an extra layer which can be achieved out side of this library. Because the purpose of this library is for providing an interface for controlling modals with the Vuex manner.

If you want to use easier interface like `$modal`, it would be better to put the `plugin` function in your own project since it allows you to custom the methods with your own needs.

**Comment by glemmaPaul** [comment]
Thanks for your response @ktsn. I can definitely see why this could be reduce your intention to keep it raw and low level, although it will add some small byte addition to the file size, it does not restrict you from actually using the most basic functionality by only attaching it as module. 

This addition is more so making it easy for other users (outsiders of your code) to create more layers around your module with just less learning curve. Having a restriction on only the flow of manually appending it does not make it better in my opinion, not using `$modal` is absolutely possible 😃 !

Lastly it includes a more extended example that we can possibly deploy to github to have users try it before installing it. I was thinking to add that functionality next week.

Because of the name `vuex-modal` and the `npm` dependency - I was thinking you were going for a certain implementation of having it as an actual easily usable module, but if this is something you want to only for personal use I can totally see where you coming from. Hope you can reconsider this addition, I really like to help here.

**Pull request closed without merging**
